### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by songproducer** [historygraphio/historygraph#16]
Running 
python -m unittest discover 
...worked before setting up a virtualenv for Python 3.

After trying the instructions for python3 and running
python3 -m unittest discover
or
python -m unittest discover:

```======================================================================
ERROR: runTest (tests.tests.UncleanReplayCounterTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/leotreasure/historygraph/tests/tests.py", line 794, in runTest
    test.testcounter.add(1)
  File "/Users/leotreasure/historygraph/historygraph/fieldintcounter.py", line 17, in add
    self.WasChanged(ChangeType.ADD_INT_COUNTER, self.parent.id, self.name, change, "FieldIntCounter")
  File "/Users/leotreasure/historygraph/historygraph/fieldintcounter.py", line 27, in WasChanged
    assert isinstance(propertyownerid, basestring)
NameError: name 'basestring' is not defined

----------------------------------------------------------------------
Ran 25 tests in 0.006s```

**Comment by mlockett42** [comment]
HistoryGraph currently only supports Python 2 there is an open issue to fix it to add Python 3 support here

https://github.com/historygraphio/historygraph/issues/6

The correct way to test for multiple versions of python is to use the Tox program. In the develop branch of this repo tox should be set up correctly. If you run it you should see it pass in Python 2 and fail in Python 3. Maybe you could try to fix this issue I don't think it is a hard one, you would just have to read up on the differences between Python 2 and 3 and how to use the Six library.

The specific reason why what you were doing is probably that if you build a python 3 virtualenv you can only run python 3 in it. Starting the python program will start Python 3 (so will python3), where as at the normal console python starts python 2 and python3 starts python 3

**Comment by mlockett42** [comment]
Done
